ORG 0000H
SETB P2.2; TURN OFF THE LED
CLR TR1; STOP TIMER 1
MOV A,TMOD;
ANL A,#0X0F;
ORL A,#0X20;
MOV TMOD,A;CONFIGURE TIMER 1 IN MODE 2 WITHOUT AFFECTING TIMER 0 OPERATION
MOV TH1,#0X9C; LOAD COUNT VALUE
MOV TL1,#0X9C; LOAD COUNT VALUE
SETB TR1; RUN TIMER 1
BLINK:JNB TF1,$; WAIT FOR TIMER 1 OVERFLOW
CLR TF1; CLEAR TIMER 1 OVERFLOW BIT
CPL P2.2; TOGGLE LED
SJMP BLINK
